### ISSUE TITLE
video "tabla dinámica" xls

### ISSUE THREAD

**Issue by dnme-minturdep** [dnme-minturdep/DT6_ciencia_de_datos_turismo#46]
**[Aparece ](https://dnme-minturdep.github.io/DT6_ciencia_de_datos_turismo/manipulaci%C3%B3n-de-datos-ordenados.html
)un *rehacer video*** 

![imagen](https://user-images.githubusercontent.com/83460881/142725102-7eb57285-5999-44eb-aeb5-e131e5a6176b.png)

**Comment by yabellini** [comment]
Se sigue viendo el texto "rehacer video" en la web y está usando el video viejo, no se que pasó con el que grabé yo unsado Excel.

**Comment by eliocamp** [comment]
Sigue porque el libro no se pudo renderizar cuando lo actualicé porque yvera estaba caído (#47)

**Comment by eliocamp** [comment]
Ahora está.
