### ISSUE TITLE
Hacer que compilar no dependa de yvera

### ISSUE THREAD

**Issue by eliocamp** [dnme-minturdep/DT6_ciencia_de_datos_turismo#47]
Estoy resolviendo otro problema pero el libro no compila porque yvera está caido y hay varios chunks que bajan los datos de ahí. Lo que habría que hacer es descargar los datos y leerlos localmente. Si queremos, podemos dejar el código que lee desde yvera pero sin evaluarlo y esconcder el que lee localmente. 

(el problema de esto es que hay que esperar que yvera esté de nuevo disponible para descargar los datos xD)

**Comment by yabellini** [comment]
Me parece bien dejar el que lee de iyvera sin evaluar y usar lo local "escondido"
