### ISSUE TITLE
Pipa nativa y notación lambda

### ISSUE THREAD

**Issue by eliocamp** [dnme-minturdep/DT6_ciencia_de_datos_turismo#5]
¿Les parece que convenga agregar algo de la pipa nativa y la notación lambda para crear funciones (`\(x)`)?

Siento que está bueno agregarlo porque va siendo parte de la sintaxis moderna de R, pero todavía no está totalmente formada (todavía no acepta el placeholder y no se sabe si en el futuro va a acpetar, por ejemplo) y usarlas en el código hace que el mismo no se pueda correr en versiones de R que no son tan viejas.

**Comment by paocorrales** [comment]
Creo que podemos mencionar la nueva pipa pero no me metería en la notación lamdda. Decidimos sacar la parte de funciones y creo que eso caería en ese capítulo.

**Comment by yabellini** [comment]
Recordemos que es un curso introductorio para gente que no programa.  Tenemos solo cuatro encuentros, no mostraría dos pipes diferentes.  Me quedaría con el de tidyverse y nada más, no haría mención al otro tampoco, es demasiada carga cognitiva sin un beneficio real para quien está aprendiendo.

**Comment by eliocamp** [comment]
Si, es cierto.

**Comment by paocorrales** [comment]
Estoy de acuerdo con ambos. Igual tengamos en cuenta estos materiales podrían tener cosas extras que tal vez no mencionemos en el curso. Creo que si la pipe nativa se empieza a usar y nos encontramos con esa sintaxis por ahí no daña agregar un recuadro con una pequeña aclaración sobre de donde sale y como se usa.
